# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '19_Action' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 19_Action
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxDataSources'
    pod 'Action'

  target '19_ActionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '19_ActionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
